'use babel';

import { CompositeDisposable } from 'atom';

const NORMAL   = 0
const SUFFIXED = 1
const BASE_URL = 'https://processing.org/reference/'

export default {

  atomP5refView: null,
  modalPanel: null,
  subscriptions: null,

  activate(state) {
      // Events subscribed to in atom's system can be easily cleaned up with a CompositeDisposable
      this.subscriptions = new CompositeDisposable();

      // Register command that toggles this view
      this.subscriptions.add(atom.commands.add('atom-workspace', {
          'atom-p5ref:look': () => this.lookFor()
      }));
  },

  REFERENCE: {
    'catch' : NORMAL,
    'class' : NORMAL,
    'draw' : SUFFIXED,
    'exit' : SUFFIXED,
    'extends' : NORMAL,
    'false' : NORMAL,
    'final' : NORMAL,
    'implement' : NORMAL,
    'import' : NORMAL,
    'loop' : SUFFIXED,
    'new' : NORMAL,
    'noLoop' : SUFFIXED,
    'null' : NORMAL,
    'popStyle' : SUFFIXED,
    'private' : NORMAL,
    'public' : NORMAL,
    'pushStyle' : SUFFIXED,
    'redraw' : SUFFIXED,
    'return' : NORMAL,
    'setup' : SUFFIXED,
    'static' : NORMAL,
    'super' : NORMAL,
    'this' : NORMAL,
    'thread' : NORMAL,
    'true' : NORMAL,
    'try' : NORMAL,
    'void' : NORMAL,
    'cursor' : SUFFIXED,
    'delay' : SUFFIXED,
    'displayDensity' : SUFFIXED,
    'focused' : NORMAL,
    'frameCount' : NORMAL,
    'frameRate' : NORMAL,
    'frameRate' : SUFFIXED,
    'fullScreen' : SUFFIXED,
    'height' : NORMAL,
    'noCursor' : SUFFIXED,
    'noSmooth' : SUFFIXED,
    'pixelDensity' : SUFFIXED,
    'pixelHeight' : NORMAL,
    'pixelWidth' : NORMAL,
    'settings' : SUFFIXED,
    'size' : SUFFIXED,
    'smooth' : SUFFIXED,
    'width' : NORMAL,
    'color' : 'color_datatype',
    'double' : NORMAL,
    'long' : NORMAL,
    'Array' :  NORMAL,
    'ArrayList' : NORMAL,
    'DoubleDict' : NORMAL,
    'DoubleList' : NORMAL,
    'FloatDict' : NORMAL,
    'FloatList' : NORMAL,
    'HashMap' : NORMAL,
    'IntDict' : NORMAL,
    'IntList' : NORMAL,
    'JSONArray' : NORMAL,
    'JSONObject' : NORMAL,
    'LongDict' : NORMAL,
    'LongList' : NORMAL,
    'Object' : NORMAL,
    'String' : NORMAL,
    'StringDict' : NORMAL,
    'StringList' : NORMAL,
    'Table' : NORMAL,
    'TableRow' : NORMAL,
    'XML' : NORMAL,
    'binary' : SUFFIXED,
    'boolean' : 'booleanconvert_',
    'byte' : 'byteconvert_',
    'char' : 'charconvert_',
    'float' : 'floatconvert_',
    'hex' : SUFFIXED,
    'int' :  'intconvert_',
    'str' :  'strconvert_',
    'unbinary' : SUFFIXED,
    'unhex' : SUFFIXED,
    'join' : SUFFIXED,
    'match' : SUFFIXED,
    'matchAll' : SUFFIXED,
    'nf' : SUFFIXED,
    'nfc' : SUFFIXED,
    'nfp' : SUFFIXED,
    'nfs' : SUFFIXED,
    'split' : SUFFIXED,
    'splitTokens' : SUFFIXED,
    'trim' : SUFFIXED,
    'append' : SUFFIXED,
    'arrayCopy' : SUFFIXED,
    'concat' : SUFFIXED,
    'expand' : SUFFIXED,
    'reverse' : SUFFIXED,
    'shorten' : SUFFIXED,
    'sort' : SUFFIXED,
    'splice' : SUFFIXED,
    'subset' : SUFFIXED,
    '!=' : 'inequality',
    '<' : 'lessthan',
    '<=' : 'lessthanorequalto',
    '==' : 'equality',
    '>' : 'greaterthan',
    '>=' : 'greaterthanorequalto',
    'for' : NORMAL,
    'while' : NORMAL,
    'break' : NORMAL,
    'case' : NORMAL,
    'continue' : NORMAL,
    'default' : NORMAL,
    'else' : NORMAL,
    'if' : NORMAL,
    'switch' : NORMAL,
    '!' : 'logicalNOT',
    '&&' : 'logicalAND',
    '||' : 'logicalOR',
    'createShape' : SUFFIXED,
    'loadShape' : SUFFIXED,
    'PShape' : SUFFIXED,
    'arc' : SUFFIXED,
    'ellipse' : SUFFIXED,
    'line' : SUFFIXED,
    'point' : SUFFIXED,
    'quad' : SUFFIXED,
    'rect' : SUFFIXED,
    'triangle' : SUFFIXED,
    'bezier' : SUFFIXED,
    'bezierDetail' : SUFFIXED,
    'bezierPoint' : SUFFIXED,
    'bezierTangent' : SUFFIXED,
    'curve' : SUFFIXED,
    'curveDetail' : SUFFIXED,
    'curvePoint' : SUFFIXED,
    'curveTangent' : SUFFIXED,
    'curveTightness' : SUFFIXED,
    'box' : SUFFIXED,
    'sphere' : SUFFIXED,
    'sphereDetail' : SUFFIXED,
    'ellipseMode' : SUFFIXED,
    'rectMode' : SUFFIXED,
    'strokeCap' : SUFFIXED,
    'strokeJoin' : SUFFIXED,
    'strokeWeight' : SUFFIXED,
    'beginContour' : SUFFIXED,
    'beginShape' : SUFFIXED,
    'bezierVertex' : SUFFIXED,
    'curveVertex' : SUFFIXED,
    'endContour' : SUFFIXED,
    'endShape' : SUFFIXED,
    'quadraticVertex' : SUFFIXED,
    'vertex' : SUFFIXED,
    'shape' : SUFFIXED,
    'shapeMode' : SUFFIXED,
    'mouseButton' : SUFFIXED,
    'mouseClicked' : SUFFIXED,
    'mouseDragged' : SUFFIXED,
    'mouseMoved' : SUFFIXED,
    'mousePressed' : SUFFIXED,
    'mousePressed' : SUFFIXED,
    'mouseReleased' : SUFFIXED,
    'mouseWheel' : SUFFIXED,
    'mouseX' : NORMAL,
    'mouseY' : NORMAL,
    'pmouseX' : NORMAL,
    'pmouseY' : NORMAL,
    'key' : NORMAL,
    'keyCode' : NORMAL,
    'keyPressed' : NORMAL,
    'keyReleased' : SUFFIXED,
    'keyTyped' : SUFFIXED,
    'BufferedReader' : NORMAL,
    'createInput' : SUFFIXED,
    'createReader' : SUFFIXED,
    'launch' : SUFFIXED,
    'loadBytes' : SUFFIXED,
    'loadJSONArray' : SUFFIXED,
    'loadJSONObject' : SUFFIXED,
    'loadStrings' : SUFFIXED,
    'loadTable' : SUFFIXED,
    'loadXML' : SUFFIXED,
    'parseJSONArray' : SUFFIXED,
    'parseJSONObject' : SUFFIXED,
    'parseXML' : SUFFIXED,
    'selectFolder' : SUFFIXED,
    'selectInput' : SUFFIXED,
    'day' : SUFFIXED,
    'hour' : SUFFIXED,
    'millis' : SUFFIXED,
    'minute' : SUFFIXED,
    'month' : SUFFIXED,
    'second' : SUFFIXED,
    'year' : SUFFIXED,
    'print' : SUFFIXED,
    'printArray' : SUFFIXED,
    'println' : SUFFIXED,
    'save' : SUFFIXED,
    'saveFrame' : SUFFIXED,
    'beginRaw' : SUFFIXED,
    'beginRecord' : SUFFIXED,
    'createOutput' : SUFFIXED,
    'createWriter' : SUFFIXED,
    'endRaw' : SUFFIXED,
    'endRecord' : SUFFIXED,
    'PrintWriter' : NORMAL,
    'saveBytes' : SUFFIXED,
    'saveJSONArray' : SUFFIXED,
    'saveJSONObject' : SUFFIXED,
    'saveStream' : SUFFIXED,
    'saveStrings' : SUFFIXED,
    'saveTable' : SUFFIXED,
    'saveXML' : SUFFIXED,
    'selectOutput' : SUFFIXED,
    'applyMatrix' : SUFFIXED,
    'popMatrix' : SUFFIXED,
    'printMatrix' : SUFFIXED,
    'pushMatrix' : SUFFIXED,
    'resetMatrix' : SUFFIXED,
    'rotate' : SUFFIXED,
    'rotateX' : SUFFIXED,
    'rotateY' : SUFFIXED,
    'rotateZ' : SUFFIXED,
    'scale' : SUFFIXED,
    'shearX' : SUFFIXED,
    'shearY' : SUFFIXED,
    'translate' : SUFFIXED,
    'ambientLight' : SUFFIXED,
    'directionalLight' : SUFFIXED,
    'lightFalloff' : SUFFIXED,
    'lights' : SUFFIXED,
    'lightSpecular' : SUFFIXED,
    'noLights' : SUFFIXED,
    'NORMAL' : SUFFIXED,
    'pointLight' : SUFFIXED,
    'spotLight' : SUFFIXED,
    'beginCamera' : SUFFIXED,
    'camera' : SUFFIXED,
    'endCamera' : SUFFIXED,
    'frustum' : SUFFIXED,
    'ortho' : SUFFIXED,
    'perspective' : SUFFIXED,
    'printCamera' : SUFFIXED,
    'printProjection' : SUFFIXED,
    'modelX' : SUFFIXED,
    'modelY' : SUFFIXED,
    'modelZ' : SUFFIXED,
    'screenX' : SUFFIXED,
    'screenY' : SUFFIXED,
    'screenZ' : SUFFIXED,
    'ambient' : SUFFIXED,
    'emissive' : SUFFIXED,
    'shininess' : SUFFIXED,
    'specular' : SUFFIXED,
    'background' : SUFFIXED,
    'clear' : SUFFIXED,
    'colorMode' : SUFFIXED,
    'fill' : SUFFIXED,
    'noFill' : SUFFIXED,
    'noStroke' : SUFFIXED,
    'stroke' : SUFFIXED,
    'alpha' : SUFFIXED,
    'blue' : SUFFIXED,
    'brightness' : SUFFIXED,
    'color' : SUFFIXED,
    'green' : SUFFIXED,
    'hue' : SUFFIXED,
    'lerpColor' : SUFFIXED,
    'red' : SUFFIXED,
    'saturation' : SUFFIXED,
    'createImage' : SUFFIXED,
    'PImage' : NORMAL,
    'image' : SUFFIXED,
    'imageMode' : SUFFIXED,
    'loadImage' : SUFFIXED,
    'noTint' : SUFFIXED,
    'requestImage' : SUFFIXED,
    'tint' : SUFFIXED,
    'texture' : SUFFIXED,
    'textureMode' : SUFFIXED,
    'textureWrap' : SUFFIXED,
    'blend' : SUFFIXED,
    'copy' : SUFFIXED,
    'filter' : SUFFIXED,
    'get' : SUFFIXED,
    'loadPixels' : SUFFIXED,
    'pixels' : NORMAL,
    'set' : SUFFIXED,
    'updatePixels' : SUFFIXED,
    'blendMode' : SUFFIXED,
    'clip' : SUFFIXED,
    'createGraphics' : SUFFIXED,
    'noClip' : SUFFIXED,
    'PGraphics' : NORMAL,
    'loadShader' : SUFFIXED,
    'PShader' : NORMAL,
    'resetShader' : SUFFIXED,
    'shader' : SUFFIXED,
    'PFont' : NORMAL,
    'createFont' : SUFFIXED,
    'loadFont' : SUFFIXED,
    'text' : SUFFIXED,
    'textFont' : SUFFIXED,
    'textAlign' : SUFFIXED,
    'textLeading' : SUFFIXED,
    'textMode' : SUFFIXED,
    'textSize' : SUFFIXED,
    'textWidth' : SUFFIXED,
    'textAscent' : SUFFIXED,
    'textDescent' : SUFFIXED,
    'PVector' : NORMAL,
    '%' : 'modulo',
    '*' : 'multiply',
    '*=' : 'multiplyassign',
    '+' : 'addition',
    '++' : 'increment',
    '+=' : 'addasign',
    '-' : 'minus',
    '--' : 'decrement',
    '-=' : 'subtractassign',
    '/' : 'divide',
    '/=' : 'divideassign',
    '&' : 'bitwiseAND',
    '<<' : 'leftshift',
    '>>' : 'rightshift',
    '|' : 'bitwiseOR',
    'abs' : SUFFIXED,
    'ceil' : SUFFIXED,
    'constrain' : SUFFIXED,
    'dist' : SUFFIXED,
    'exp' : SUFFIXED,
    'floor' : SUFFIXED,
    'lerp' : SUFFIXED,
    'log' : SUFFIXED,
    'mag' : SUFFIXED,
    'map' : SUFFIXED,
    'max' : SUFFIXED,
    'min' : SUFFIXED,
    'norm' : SUFFIXED,
    'pow' : SUFFIXED,
    'round' : SUFFIXED,
    'sq' : SUFFIXED,
    'sqrt' : SUFFIXED,
    'acos' : SUFFIXED,
    'asin' : SUFFIXED,
    'atan' : SUFFIXED,
    'atan2' : SUFFIXED,
    'cos' : SUFFIXED,
    'degrees' : SUFFIXED,
    'radians' : SUFFIXED,
    'sin' : SUFFIXED,
    'tan' : SUFFIXED,
    'noise' : SUFFIXED,
    'noiseDetail' : SUFFIXED,
    'noiseSeed' : SUFFIXED,
    'random' : SUFFIXED,
    'randomGaussian' : SUFFIXED,
    'randomSeed' : SUFFIXED,
    'HALF_PI' : 'HALF_PI',
    'PI' : 'PI',
    'QUARTER_PI' : 'QUARTER_PI',
    'TAU' : 'TAU',
    'TWO_PI' : 'TWO_PI',
  },

  url(query){
    return BASE_URL + query + '.html'
  },

  getUrl(query) {
    query = query.trim().replace('(','').replace(')','').trim()
    if(query in this.REFERENCE) {
      switch(this.REFERENCE[query]){
        case NORMAL:
          return this.url(query)
          break;
        case SUFFIXED:
          return this.url(query+'_')
          break;
        default:
          return this.url(this.REFERENCE[query])
          break;
      }
    } else {
      return null;
    }
  },

  lookFor() {
       const editor = atom.workspace.getActiveTextEditor()
       var url = this.getUrl(editor.getSelectedText())
       if(url)
          atom.workspace.open(url)
       else
          atom.notifications.addError('I cannot find that query in the Processing\'s online reference')
  },

};
